# TODO サンプルのmigrationファイル。クローン後は削除すること。
"""empty message

Revision ID: d7046e817491
Revises: 
Create Date: 2024-02-13 19:39:43.964920

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from method import create_schema, add_user_record

# revision identifiers, used by Alembic.
revision: str = "d7046e817491"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.execute(create_schema("sample"))
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False, comment="id"),
        sa.Column("user_name", sa.String(length=100), nullable=False, comment="ユーザ名"),
        sa.Column("mail", sa.String(length=100), nullable=False, comment="メールアドレス"),
        sa.Column("comment", sa.String(length=200), nullable=False, comment="コメント"),
        sa.PrimaryKeyConstraint("id"),
        schema="sample",
        comment="ユーザ",
    )
    op.create_table(
        "user_2",
        sa.Column("user_id", sa.Integer(), nullable=False, comment="user_id"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["sample.user.id"],
        ),
        sa.PrimaryKeyConstraint("user_id"),
        schema="sample",
        comment="ユーザ2",
    )
    # ### end Alembic commands ###
    op.execute(add_user_record())


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_2", schema="sample")
    op.drop_table("user", schema="sample")
    # ### end Alembic commands ###
